# Generated by Django 2.2.4 on 2019-11-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=10)),
                ('RollNo', models.IntegerField()),
                ('Phone', models.IntegerField()),
                ('Topic', models.CharField(max_length=20)),
            ],
        ),
    ]
