# Generated by Django 2.2.4 on 2019-11-02 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='RollNo',
            new_name='rollno',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Topic',
            new_name='topic',
        ),
    ]
