# Generated by Django 2.2.4 on 2019-11-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importapp', '0003_auto_20191102_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.IntegerField(default=1),
        ),
    ]
